import * as React from "react";

import { relayClient as defaultRelayClient } from "@/shared/api/relayClient";
import type {
  ConnectionState,
  RelaySubscriptionFilter,
} from "@/shared/api/relayClientShared";
import type { RelayEvent } from "@/shared/api/types";
import { armCodingSessionDiscoveryOnConnect } from "./lib/codingSessionDiscoveryArming";
import { createCodingSessionDiscoveryController } from "./lib/codingSessionDiscoveryRetry";
import {
  subscribeToAcceptedCodingSessionNames,
  type CodingSessionName,
} from "./lib/codingSessionName";
import {
  buildCodingSessionDisplayNameFilter,
  type CodingSessionDisplayNames,
  type CodingSessionGeneratedTitle,
  type CodingSessionTitleStandingQuery,
  codingSessionTitleStandingQueries,
  confirmedTitleStandingTargets,
  foldCodingSessionNames,
  readCodingSessionTitleStanding,
  TITLE_STANDING_MAX_PAGES,
  TITLE_STANDING_PAGE_LIMIT,
} from "./lib/codingSessionTitle";

const NAME_HISTORY_LIMIT = 1000;

type NameClient = {
  fetchEventsCoalesced(filter: RelaySubscriptionFilter): Promise<RelayEvent[]>;
  subscribeLive(
    filter: RelaySubscriptionFilter,
    onEvent: (event: RelayEvent) => void,
  ): Promise<() => void>;
  subscribeToReconnects?(listener: () => void): () => void;
  subscribeToConnectionState?(
    listener: (state: ConnectionState) => void,
  ): () => void;
};

/**
 * The name to show for every session in scope, and whose words it is.
 *
 * `names` is keyed by {@link codingSessionNameKey} `(channel, sessionRef,
 * founder)` as it always was; each value is the **effective** display name
 * (SV-31): the founder's own 44229 when there is one, else the earliest 44252
 * title generated by a provider with standing in that session, with
 * `origin`, `model` and `signerPubkey` saying which. A person's name always
 * wins, however old. Anything that asks "did a person already name this?" —
 * a field that would publish a 44229 over it — reads `personNames`, which
 * never holds a generated title.
 *
 * Standing is checked here, because this hook cannot see the umbrella's
 * catalog: a 44252 counts only when its signer also signed a 44223 in the
 * same channels whose `cs-target` is the title's and whose `sessionRef` is its
 * `d`, and a 44224 lifecycle receipt confirming that same generation — the
 * proof `bee sessions` and Pulse require. A title without standing is ignored
 * and counted in `titleDiagnostics`. Standing is read per `(channel, signer)`
 * backwards from the newest title it vouches for, never as "the signer's
 * latest N records": a busy provider's later turn receipts would otherwise
 * push an old session's create receipt out of the window and unseat its title.
 *
 * Same read discipline as {@link useCodingSessionClosures}, and for the same
 * reason: a name that never loads does not leave a gap on the shelf, it leaves
 * the provider's generic label sitting where the person's own words belong.
 *
 * `resolved` mirrors {@link useCodingSessionGoals}: true only once the history
 * read settled — resolved *or* rejected — so a field that publishes a 44229
 * can refuse to do so over a wire name it has not read yet. It says nothing
 * about whether a name was found.
 */
export function useCodingSessionNames(
  channelIds: readonly string[],
  client: NameClient = defaultRelayClient,
): {
  /** Effective name per founder key: the person's 44229, else a standing 44252. */
  names: CodingSessionDisplayNames;
  /** Founder-keyed 44229s only — the guard for "a person already named it". */
  personNames: Map<string, CodingSessionName>;
  /** The standing generated title per `${channelId}\u0000${sessionRef}`. */
  generatedTitles: Map<string, CodingSessionGeneratedTitle>;
  /** 44252s set aside: no standing (`foreignTitles`) or malformed. */
  titleDiagnostics: { foreignTitles: number; malformed: number };
  errorMessage: string | null;
  /** True only once the history fetch settled — resolved *or* rejected. */
  resolved: boolean;
  /** History failure or incomplete coverage; distinct from a failed live watch. */
  readErrorMessage: string | null;
  /** Recheck history and retry a failed live watch without replacing this scope. */
  refresh: () => void;
} {
  const scope = [...new Set(channelIds)].sort().join("\u0000");
  const stableChannelIds = React.useMemo(
    () => (scope ? scope.split("\u0000") : []),
    [scope],
  );
  const [events, setEvents] = React.useState<Map<string, RelayEvent>>(
    () => new Map(),
  );
  const [errorMessage, setErrorMessage] = React.useState<string | null>(null);
  const [resolved, setResolved] = React.useState(false);
  const [readErrorMessage, setReadErrorMessage] = React.useState<string | null>(
    null,
  );
  const [readScope, setReadScope] = React.useState(scope);
  const refreshRead = React.useRef<(() => void) | null>(null);
  const [metadata, setMetadata] = React.useState<Map<string, RelayEvent>>(
    () => new Map(),
  );
  const [standingError, setStandingError] = React.useState<string | null>(null);
  const [refreshCount, setRefreshCount] = React.useState(0);
  // What the standing reads found in this scope; a confirmed claim is never
  // re-read (standing, once proven by signed records, does not lapse).
  const standingEvents = React.useRef<Map<string, RelayEvent>>(new Map());
  const refresh = React.useCallback(() => {
    refreshRead.current?.();
    setRefreshCount((count) => count + 1);
  }, []);

  React.useEffect(() => {
    let cancelled = false;
    let unsubscribeLive: (() => void) | null = null;
    let liveSubscribePending = false;
    let historyError: string | null = null;
    let liveError: string | null = null;
    let historyAtLimit = false;
    setReadScope(scope);
    setReadErrorMessage(null);
    setEvents(new Map());
    // A new scope starts with no standing; old metadata never vouches here.
    setMetadata(new Map());
    standingEvents.current = new Map();
    setStandingError(null);
    setErrorMessage(null);
    // A new scope is a new read; nothing to read is the one scope that
    // starts settled.
    setResolved(stableChannelIds.length === 0);
    if (stableChannelIds.length === 0) return;

    const publishError = () => {
      if (cancelled) return;
      const readError =
        historyError ??
        (historyAtLimit
          ? `Only the latest ${NAME_HISTORY_LIMIT} name and title records were read; older session names may be missing.`
          : null);
      setReadErrorMessage(readError);
      setErrorMessage(
        readError && liveError
          ? `${readError}\n${liveError}`
          : (readError ?? liveError),
      );
    };
    const admit = (incoming: readonly RelayEvent[]) => {
      if (cancelled) return;
      setEvents((current) => {
        const next = new Map(current);
        for (const event of incoming) next.set(event.id, event);
        return next;
      });
    };

    const historyController = createCodingSessionDiscoveryController({
      async load() {
        const history = await client.fetchEventsCoalesced(
          buildCodingSessionDisplayNameFilter(
            stableChannelIds,
            NAME_HISTORY_LIMIT,
          ),
        );
        if (cancelled) return;
        admit(history);
        return history.length;
      },
      onAttemptStart() {
        if (!cancelled) setResolved(false);
      },
      onSuccess(count) {
        historyError = null;
        historyAtLimit = (count ?? 0) >= NAME_HISTORY_LIMIT;
        publishError();
        if (!cancelled) setResolved(true);
      },
      onError(error, retry) {
        // A scheduled retry is not yet a failure worth reporting.
        historyError = retry.willRetry
          ? null
          : error instanceof Error
            ? error.message
            : "Failed to load session names.";
        publishError();
        // A final failure is a settled read: the relay answered, badly.
        if (!cancelled && !retry.willRetry) setResolved(true);
      },
      retrySeed: `names:${scope}`,
    });

    const establishLive = () => {
      if (cancelled || unsubscribeLive || liveSubscribePending) return;
      liveSubscribePending = true;
      client
        .subscribeLive(
          // Bounded replay closes the gap after the independent HTTP read.
          // Subscription resolution can be a timeout, not server readiness.
          buildCodingSessionDisplayNameFilter(
            stableChannelIds,
            NAME_HISTORY_LIMIT,
          ),
          (event) => admit([event]),
        )
        .then((unsubscribe) => {
          liveSubscribePending = false;
          if (cancelled) {
            unsubscribe();
            return;
          }
          unsubscribeLive = unsubscribe;
          liveError = null;
          publishError();
        })
        .catch((error: unknown) => {
          liveSubscribePending = false;
          if (cancelled) return;
          liveError =
            error instanceof Error
              ? error.message
              : "Failed to watch session names.";
          publishError();
          // Degrade to history-only discovery when live setup fails.
          historyController.request();
        });
    };

    const refreshScope = () => {
      if (cancelled) return;
      historyController.request();
      establishLive();
    };
    refreshRead.current = refreshScope;
    refreshScope();
    const disarm = armCodingSessionDiscoveryOnConnect(client, refreshScope);
    const unsubscribeAccepted = subscribeToAcceptedCodingSessionNames(
      (event) => {
        if (
          event.tags.some(
            (tag) => tag[0] === "h" && stableChannelIds.includes(tag[1]),
          )
        )
          admit([event]);
      },
      client,
    );
    return () => {
      cancelled = true;
      if (refreshRead.current === refreshScope) refreshRead.current = null;
      historyController.cancel();
      unsubscribeLive?.();
      disarm();
      unsubscribeAccepted();
    };
  }, [client, scope, stableChannelIds]);

  // One standing read per (channel, signer), bounded by the titles it vouches
  // for; a new claim or a newer title re-reads.
  const standingQueries = React.useMemo(
    () => codingSessionTitleStandingQueries(events.values()),
    [events],
  );
  const standingKey = JSON.stringify(standingQueries);
  React.useEffect(() => {
    void refreshCount;
    const queries = JSON.parse(
      standingKey,
    ) as CodingSessionTitleStandingQuery[];
    const known = [...standingEvents.current.values()];
    const pending = queries.filter(
      (query) =>
        confirmedTitleStandingTargets(query, known).size <
        query.targetKeys.length,
    );
    if (stableChannelIds.length === 0 || pending.length === 0) return;
    let cancelled = false;
    readCodingSessionTitleStanding(pending, (filter) =>
      client.fetchEventsCoalesced(filter),
    )
      .then((read) => {
        if (cancelled) return;
        for (const event of read.events) {
          standingEvents.current.set(event.id, event);
        }
        setMetadata((current) => {
          const next = new Map(current);
          for (const event of read.events) next.set(event.id, event);
          return next;
        });
        setStandingError(
          read.incomplete
            ? `Stopped after ${TITLE_STANDING_MAX_PAGES * TITLE_STANDING_PAGE_LIMIT} provider records without finding where some sessions began; their generated titles are hidden.`
            : null,
        );
      })
      .catch((error: unknown) => {
        if (cancelled) return;
        setStandingError(
          `Could not check which providers may title these sessions, so generated titles are hidden: ${
            error instanceof Error ? error.message : String(error)
          }`,
        );
      });
    return () => {
      cancelled = true;
    };
  }, [client, refreshCount, standingKey, stableChannelIds]);

  const folded = React.useMemo(
    () =>
      foldCodingSessionNames({
        events: events.values(),
        metadata: metadata.values(),
      }),
    [events, metadata],
  );
  const currentError = readScope === scope ? errorMessage : null;
  return React.useMemo(
    () => ({
      names: folded.names,
      personNames: folded.personNames,
      generatedTitles: folded.generatedTitles,
      titleDiagnostics: folded.titleDiagnostics,
      errorMessage:
        currentError && standingError
          ? `${currentError}\n${standingError}`
          : (currentError ?? standingError),
      resolved: readScope === scope && resolved,
      readErrorMessage: readScope === scope ? readErrorMessage : null,
      refresh,
    }),
    [
      currentError,
      folded,
      readErrorMessage,
      standingError,
      readScope,
      refresh,
      resolved,
      scope,
    ],
  );
}
