/**
 * The shared prose-join vectors, run through **this** client's projection.
 *
 * `conformance/transcript-prose-join/fixtures/vectors.json` is generated by
 * the real Rust translator (and hand-written attribution cases) and read by
 * every reader of `assistant_text` (CONTRACT.md § Readers). Loaded the way
 * `recordConformance.test.mjs` loads the record vectors: from the repository
 * root, relative to `web/`, never copied. Each vector's envelopes go through
 * `projectCodingSessionTranscript` grouped per (signer, exact target) — the
 * grouping the catalog applies — and the liveness inputs through the same
 * rule-7 function the surface uses.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { test } from "node:test";

import { projectCodingSessionTranscript } from "./transcriptProjection.ts";
import {
  applyCodingSessionTranscriptArriving,
  codingSessionGenerationTranscript,
  isTranscriptTargetLive,
  joinTranscriptProse,
} from "./transcriptProseJoin.ts";

const fixture = JSON.parse(
  readFileSync(
    resolve(
      process.cwd(),
      "../conformance/transcript-prose-join/fixtures/vectors.json",
    ),
    "utf8",
  ),
);

const PROSE_TITLES = new Set([
  "Assistant",
  "Subagent",
  "Reasoning",
  "Subagent reasoning",
]);

function streamKey(signer, target) {
  return JSON.stringify([
    signer,
    target.driver,
    target.instanceId,
    target.sessionId,
    target.generation,
  ]);
}

function sameTarget(left, right) {
  return (
    left.driver === right.driver &&
    left.instanceId === right.instanceId &&
    left.sessionId === right.sessionId &&
    left.generation === right.generation
  );
}

/** Project one vector the way the browser observer does, then resolve rule 7. */
function readVector(vector) {
  const streams = new Map();
  for (const envelope of vector.input) {
    const target = envelope.content.session;
    const key = streamKey(envelope.signer, target);
    const stream = streams.get(key) ?? {
      signer: envelope.signer,
      target,
      envelopes: [],
    };
    stream.envelopes.push({
      target,
      eventSeq: envelope.content.eventSeq,
      timestamp: envelope.content.timestamp,
      turnId: envelope.content.turnId,
      item: envelope.content.item,
      eventId: envelope.eventId,
    });
    streams.set(key, stream);
  }
  const ordered = [...streams.values()].sort((left, right) =>
    streamKey(left.signer, left.target) < streamKey(right.signer, right.target)
      ? -1
      : 1,
  );
  const messages = [];
  for (const stream of ordered) {
    const rows = projectCodingSessionTranscript(stream.envelopes, {
      blockKey: `${stream.signer}|block`,
    });
    const superseded = [...streams.values()].some(
      (other) =>
        other.signer === stream.signer &&
        other.target.driver === stream.target.driver &&
        other.target.instanceId === stream.target.instanceId &&
        other.target.sessionId === stream.target.sessionId &&
        other.target.generation > stream.target.generation,
    );
    const status =
      vector.sessionStatus.find(
        (entry) =>
          entry.signer === stream.signer &&
          sameTarget(entry.target, stream.target),
      )?.status ?? null;
    const lease =
      vector.sessionLease.find(
        (entry) =>
          entry.signer === stream.signer &&
          sameTarget(entry.target, stream.target),
      )?.lease ?? null;
    const live = isTranscriptTargetLive({ superseded, status, lease });
    for (const row of applyCodingSessionTranscriptArriving(rows, live)) {
      if (row.firstEventId === undefined) continue;
      messages.push({ row, signer: stream.signer, target: stream.target });
    }
  }
  return messages;
}

test("the fixture is the shared one, and names this reader", () => {
  assert.equal(fixture.schema, "buzz.conformance/transcript-prose-join@1");
  assert.ok(fixture.vectors.length >= 15);
  const contract = readFileSync(
    resolve(process.cwd(), "../conformance/transcript-prose-join/CONTRACT.md"),
    "utf8",
  );
  assert.match(contract, /web\/src\/features\/coding-sessions\/domain/);
});

for (const vector of fixture.vectors) {
  test(`prose-join vector ${vector.name}`, () => {
    const actual = readVector(vector);
    assert.equal(
      actual.length,
      vector.expectedMessages.length,
      `${vector.name}: message count`,
    );
    vector.expectedMessages.forEach((expected, index) => {
      const { row, signer, target } = actual[index];
      const where = `${vector.name} message ${index}`;
      assert.equal(row.firstEventId, expected.firstEventId, `${where} first`);
      assert.equal(row.lastEventId, expected.lastEventId, `${where} last`);
      assert.equal(row.text, expected.text, `${where} text, byte for byte`);
      assert.equal(row.turnId, expected.turnId, `${where} turnId`);
      assert.equal(
        row.parentToolId ?? null,
        expected.parentToolId,
        `${where} parentToolId`,
      );
      assert.equal(signer, expected.signer, `${where} signer`);
      assert.deepEqual(target, expected.target, `${where} target`);
      assert.equal(row.arriving, expected.arriving, `${where} arriving`);
      assert.equal(row.role, "assistant", `${where} role`);
      assert.ok(PROSE_TITLES.has(row.title), `${where} title`);
      const reasoning = expected.kind === "reasoning";
      const subagent = expected.parentToolId !== null;
      assert.equal(
        row.title,
        reasoning
          ? subagent
            ? "Subagent reasoning"
            : "Reasoning"
          : subagent
            ? "Subagent"
            : "Assistant",
        `${where} attribution`,
      );
    });
  });
}

test("the vectors exercise both arriving outcomes", () => {
  const all = fixture.vectors.flatMap((vector) => vector.expectedMessages);
  assert.ok(all.some((message) => message.arriving === true));
  assert.ok(all.some((message) => message.arriving === false));
});

// ── Rule 7, past the vectors ────────────────────────────────────────────────

const TARGET = {
  driver: "d",
  instanceId: "i",
  sessionId: "s",
  generation: 1,
};

function piece(eventSeq, item, turnId = "turn-1") {
  return {
    target: TARGET,
    eventSeq,
    timestamp: eventSeq,
    turnId,
    item,
    eventId: `e${eventSeq}`,
  };
}

const OPEN_TURN = [
  piece(1, { kind: "user_prompt", content: "go" }),
  piece(2, { kind: "assistant_text", text: "one\n\n" }),
  piece(3, { kind: "assistant_text", text: "two\n\n" }),
  piece(4, { kind: "assistant_text", text: "three" }),
];

test("an open turn's trailing message awaits its end, but is not arriving on its own", () => {
  const rows = projectCodingSessionTranscript(OPEN_TURN);
  assert.equal(rows.length, 2);
  assert.equal(rows[1].text, "one\n\ntwo\n\nthree");
  assert.equal(rows[1].awaitingTurnEnd, true);
  assert.equal(
    rows[1].arriving,
    false,
    "no lease read: turn state alone never says anyone is writing",
  );
});

test("liveness: only a live lease on an unsuperseded, unended target", () => {
  const live = { superseded: false, status: "running", lease: "live" };
  assert.equal(isTranscriptTargetLive(live), true);
  assert.equal(isTranscriptTargetLive({ ...live, status: null }), true);
  for (const status of ["interrupted", "failed", "idle", "unknown"]) {
    assert.equal(
      isTranscriptTargetLive({ ...live, status }),
      true,
      `${status} ends a turn, not the session`,
    );
  }
  for (const status of ["completed", "stopped", "disconnected"]) {
    assert.equal(isTranscriptTargetLive({ ...live, status }), false, status);
  }
  for (const lease of ["released", "lapsed", null]) {
    assert.equal(isTranscriptTargetLive({ ...live, lease }), false, lease);
  }
  assert.equal(isTranscriptTargetLive({ ...live, superseded: true }), false);
});

test("the surface's call: provider_reachable is the only report that shows Writing…", () => {
  const transcript = projectCodingSessionTranscript(OPEN_TURN);
  const report = (reachability) => ({
    reachability,
    lastReportedStatus: "running",
    lastReportedAgeSeconds: 1,
  });
  const arriving = (generation, rep) =>
    codingSessionGenerationTranscript(generation, rep).map(
      (row) => row.arriving === true,
    );
  const running = { status: "running", transcript };
  assert.deepEqual(arriving(running, report("provider_reachable")), [
    false,
    true,
  ]);
  assert.deepEqual(arriving(running, report("unknown")), [false, false]);
  assert.deepEqual(arriving(running, report("no_provider_answering")), [
    false,
    false,
  ]);
  assert.deepEqual(arriving(running, undefined), [false, false]);
  assert.deepEqual(
    arriving({ status: "stopped", transcript }, report("provider_reachable")),
    [false, false],
    "a session-ending status beats a lease",
  );
});

test("a result clears it; an item after the prose means it is not the turn's tail", () => {
  const settled = projectCodingSessionTranscript([
    ...OPEN_TURN,
    piece(5, { kind: "result", subtype: "success", result: "done" }),
  ]);
  assert.equal(settled[1].awaitingTurnEnd, false);
  const toolAfter = projectCodingSessionTranscript([
    ...OPEN_TURN,
    piece(5, {
      kind: "tool_call",
      tool: { toolName: "Bash", toolId: "c1", input: {} },
    }),
  ]);
  assert.equal(toolAfter[1].awaitingTurnEnd, false);
  const noTurn = projectCodingSessionTranscript([
    piece(1, { kind: "assistant_text", text: "loose" }, null),
  ]);
  assert.equal(noTurn[0].awaitingTurnEnd, false, "turnId null never arrives");
});

test("a paired tool_result still splits the prose around it", () => {
  // call, prose, result, prose: the result folds into the call's row, so a
  // pass over rows alone would see two adjacent pieces and join them.
  const rows = projectCodingSessionTranscript([
    piece(1, {
      kind: "tool_call",
      tool: { toolName: "Bash", toolId: "c1", input: {} },
    }),
    piece(2, { kind: "assistant_text", text: "before " }),
    piece(3, { kind: "tool_result", toolId: "c1", content: "ok" }),
    piece(4, { kind: "assistant_text", text: "after" }),
  ]);
  assert.deepEqual(
    rows.map((row) => row.text),
    ["", "before ", "after"],
  );
  assert.equal(rows[0].tool.status, "completed");
});

test("the joined row keeps the first piece's identity as later pieces arrive", () => {
  const first = projectCodingSessionTranscript(OPEN_TURN.slice(0, 2));
  const later = projectCodingSessionTranscript(OPEN_TURN);
  assert.equal(first[1].id, later[1].id, "the row stays mounted");
  assert.equal(later[1].firstEventId, "e2");
  assert.equal(later[1].lastEventId, "e4");
});

test("the join is pure: rows and entries are not mutated", () => {
  const rows = projectCodingSessionTranscript([
    piece(1, { kind: "assistant_text", text: "a" }),
  ]);
  const snapshot = JSON.stringify(rows);
  const entries = [
    {
      rowIndex: 0,
      targetKey: "t",
      turnId: "turn-1",
      kind: "assistant_text",
      parentToolId: null,
      messageId: null,
    },
  ];
  joinTranscriptProse(rows, entries);
  assert.equal(JSON.stringify(rows), snapshot);
});
