// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as remindersRouteImport } from "./routes/reminders";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as projectsRouteImport } from "./routes/projects";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as agentProgressRouteImport } from "./routes/agent-progress";
import { Route as indexRouteImport } from "./routes/index";
import { Route as workflowsDotworkflowIdRouteImport } from "./routes/workflows.$workflowId";
import { Route as shellDotsessionIdRouteImport } from "./routes/shell.$sessionId";
import { Route as projectsDotprojectIdRouteImport } from "./routes/projects.$projectId";
import { Route as messagesDotnewRouteImport } from "./routes/messages.new";
import { Route as codingSessionsDotnewRouteImport } from "./routes/coding-sessions.new";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";
import { Route as projectsDotprojectIdDotindexRouteImport } from "./routes/projects.$projectId.index";
import { Route as projectsDotprojectIdDottodosRouteImport } from "./routes/projects.$projectId.todos";
import { Route as projectsDotprojectIdDotpulseRouteImport } from "./routes/projects.$projectId.pulse";
import { Route as projectsDotprojectIdDotpacksRouteImport } from "./routes/projects.$projectId.packs";
import { Route as projectsDotprojectIdDotcontributorsRouteImport } from "./routes/projects.$projectId.contributors";
import { Route as projectsDotprojectIdDotagentsRouteImport } from "./routes/projects.$projectId.agents";
import { Route as observeDotownerDotsessionIdRouteImport } from "./routes/observe.$owner.$sessionId";
import { Route as codingSessionsDotchannelIdDotgenerationIdRouteImport } from "./routes/coding-sessions.$channelId.$generationId";
import { Route as projectsDotprojectIdDotsessionsDotnewRouteImport } from "./routes/projects.$projectId.sessions.new";
import { Route as projectsDotprojectIdDotcodeDotrepoIdRouteImport } from "./routes/projects.$projectId.code.$repoId";
import { Route as codingSessionsDotchannelIdDotfoundedDotsessionRefRouteImport } from "./routes/coding-sessions.$channelId.founded.$sessionRef";
import { Route as channelsDotchannelIdDotpostsDotpostIdRouteImport } from "./routes/channels.$channelId.posts.$postId";

const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const remindersRoute = remindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => rootRouteImport,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsRoute = projectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const agentProgressRoute = agentProgressRouteImport.update({
  id: "/agent-progress",
  path: "/agent-progress",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const workflowsDotworkflowIdRoute = workflowsDotworkflowIdRouteImport.update({
  id: "/workflows/$workflowId",
  path: "/workflows/$workflowId",
  getParentRoute: () => rootRouteImport,
} as any);
const shellDotsessionIdRoute = shellDotsessionIdRouteImport.update({
  id: "/shell/$sessionId",
  path: "/shell/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsDotprojectIdRoute = projectsDotprojectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const messagesDotnewRoute = messagesDotnewRouteImport.update({
  id: "/messages/new",
  path: "/messages/new",
  getParentRoute: () => rootRouteImport,
} as any);
const codingSessionsDotnewRoute = codingSessionsDotnewRouteImport.update({
  id: "/coding-sessions/new",
  path: "/coding-sessions/new",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsDotprojectIdDotindexRoute =
  projectsDotprojectIdDotindexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const projectsDotprojectIdDottodosRoute =
  projectsDotprojectIdDottodosRouteImport.update({
    id: "/todos",
    path: "/todos",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const projectsDotprojectIdDotpulseRoute =
  projectsDotprojectIdDotpulseRouteImport.update({
    id: "/pulse",
    path: "/pulse",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const projectsDotprojectIdDotpacksRoute =
  projectsDotprojectIdDotpacksRouteImport.update({
    id: "/packs",
    path: "/packs",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const projectsDotprojectIdDotcontributorsRoute =
  projectsDotprojectIdDotcontributorsRouteImport.update({
    id: "/contributors",
    path: "/contributors",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const projectsDotprojectIdDotagentsRoute =
  projectsDotprojectIdDotagentsRouteImport.update({
    id: "/agents",
    path: "/agents",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const observeDotownerDotsessionIdRoute =
  observeDotownerDotsessionIdRouteImport.update({
    id: "/observe/$owner/$sessionId",
    path: "/observe/$owner/$sessionId",
    getParentRoute: () => rootRouteImport,
  } as any);
const codingSessionsDotchannelIdDotgenerationIdRoute =
  codingSessionsDotchannelIdDotgenerationIdRouteImport.update({
    id: "/coding-sessions/$channelId/$generationId",
    path: "/coding-sessions/$channelId/$generationId",
    getParentRoute: () => rootRouteImport,
  } as any);
const projectsDotprojectIdDotsessionsDotnewRoute =
  projectsDotprojectIdDotsessionsDotnewRouteImport.update({
    id: "/sessions/new",
    path: "/sessions/new",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const projectsDotprojectIdDotcodeDotrepoIdRoute =
  projectsDotprojectIdDotcodeDotrepoIdRouteImport.update({
    id: "/code/$repoId",
    path: "/code/$repoId",
    getParentRoute: () => projectsDotprojectIdRoute,
  } as any);
const codingSessionsDotchannelIdDotfoundedDotsessionRefRoute =
  codingSessionsDotchannelIdDotfoundedDotsessionRefRouteImport.update({
    id: "/coding-sessions/$channelId/founded/$sessionRef",
    path: "/coding-sessions/$channelId/founded/$sessionRef",
    getParentRoute: () => rootRouteImport,
  } as any);
const channelsDotchannelIdDotpostsDotpostIdRoute =
  channelsDotchannelIdDotpostsDotpostIdRouteImport.update({
    id: "/channels/$channelId/posts/$postId",
    path: "/channels/$channelId/posts/$postId",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agent-progress": typeof agentProgressRoute;
  "/agents": typeof agentsRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/coding-sessions/new": typeof codingSessionsDotnewRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRouteWithChildren;
  "/shell/$sessionId": typeof shellDotsessionIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/coding-sessions/$channelId/$generationId": typeof codingSessionsDotchannelIdDotgenerationIdRoute;
  "/observe/$owner/$sessionId": typeof observeDotownerDotsessionIdRoute;
  "/projects/$projectId/agents": typeof projectsDotprojectIdDotagentsRoute;
  "/projects/$projectId/contributors": typeof projectsDotprojectIdDotcontributorsRoute;
  "/projects/$projectId/packs": typeof projectsDotprojectIdDotpacksRoute;
  "/projects/$projectId/pulse": typeof projectsDotprojectIdDotpulseRoute;
  "/projects/$projectId/todos": typeof projectsDotprojectIdDottodosRoute;
  "/projects/$projectId/": typeof projectsDotprojectIdDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
  "/coding-sessions/$channelId/founded/$sessionRef": typeof codingSessionsDotchannelIdDotfoundedDotsessionRefRoute;
  "/projects/$projectId/code/$repoId": typeof projectsDotprojectIdDotcodeDotrepoIdRoute;
  "/projects/$projectId/sessions/new": typeof projectsDotprojectIdDotsessionsDotnewRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agent-progress": typeof agentProgressRoute;
  "/agents": typeof agentsRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/coding-sessions/new": typeof codingSessionsDotnewRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/shell/$sessionId": typeof shellDotsessionIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/coding-sessions/$channelId/$generationId": typeof codingSessionsDotchannelIdDotgenerationIdRoute;
  "/observe/$owner/$sessionId": typeof observeDotownerDotsessionIdRoute;
  "/projects/$projectId/agents": typeof projectsDotprojectIdDotagentsRoute;
  "/projects/$projectId/contributors": typeof projectsDotprojectIdDotcontributorsRoute;
  "/projects/$projectId/packs": typeof projectsDotprojectIdDotpacksRoute;
  "/projects/$projectId/pulse": typeof projectsDotprojectIdDotpulseRoute;
  "/projects/$projectId/todos": typeof projectsDotprojectIdDottodosRoute;
  "/projects/$projectId": typeof projectsDotprojectIdDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
  "/coding-sessions/$channelId/founded/$sessionRef": typeof codingSessionsDotchannelIdDotfoundedDotsessionRefRoute;
  "/projects/$projectId/code/$repoId": typeof projectsDotprojectIdDotcodeDotrepoIdRoute;
  "/projects/$projectId/sessions/new": typeof projectsDotprojectIdDotsessionsDotnewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/agent-progress": typeof agentProgressRoute;
  "/agents": typeof agentsRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/coding-sessions/new": typeof codingSessionsDotnewRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRouteWithChildren;
  "/shell/$sessionId": typeof shellDotsessionIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/coding-sessions/$channelId/$generationId": typeof codingSessionsDotchannelIdDotgenerationIdRoute;
  "/observe/$owner/$sessionId": typeof observeDotownerDotsessionIdRoute;
  "/projects/$projectId/agents": typeof projectsDotprojectIdDotagentsRoute;
  "/projects/$projectId/contributors": typeof projectsDotprojectIdDotcontributorsRoute;
  "/projects/$projectId/packs": typeof projectsDotprojectIdDotpacksRoute;
  "/projects/$projectId/pulse": typeof projectsDotprojectIdDotpulseRoute;
  "/projects/$projectId/todos": typeof projectsDotprojectIdDottodosRoute;
  "/projects/$projectId/": typeof projectsDotprojectIdDotindexRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
  "/coding-sessions/$channelId/founded/$sessionRef": typeof codingSessionsDotchannelIdDotfoundedDotsessionRefRoute;
  "/projects/$projectId/code/$repoId": typeof projectsDotprojectIdDotcodeDotrepoIdRoute;
  "/projects/$projectId/sessions/new": typeof projectsDotprojectIdDotsessionsDotnewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agent-progress"
    | "/agents"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/channels/$channelId"
    | "/coding-sessions/new"
    | "/messages/new"
    | "/projects/$projectId"
    | "/shell/$sessionId"
    | "/workflows/$workflowId"
    | "/coding-sessions/$channelId/$generationId"
    | "/observe/$owner/$sessionId"
    | "/projects/$projectId/agents"
    | "/projects/$projectId/contributors"
    | "/projects/$projectId/packs"
    | "/projects/$projectId/pulse"
    | "/projects/$projectId/todos"
    | "/projects/$projectId/"
    | "/channels/$channelId/posts/$postId"
    | "/coding-sessions/$channelId/founded/$sessionRef"
    | "/projects/$projectId/code/$repoId"
    | "/projects/$projectId/sessions/new";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agent-progress"
    | "/agents"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/channels/$channelId"
    | "/coding-sessions/new"
    | "/messages/new"
    | "/shell/$sessionId"
    | "/workflows/$workflowId"
    | "/coding-sessions/$channelId/$generationId"
    | "/observe/$owner/$sessionId"
    | "/projects/$projectId/agents"
    | "/projects/$projectId/contributors"
    | "/projects/$projectId/packs"
    | "/projects/$projectId/pulse"
    | "/projects/$projectId/todos"
    | "/projects/$projectId"
    | "/channels/$channelId/posts/$postId"
    | "/coding-sessions/$channelId/founded/$sessionRef"
    | "/projects/$projectId/code/$repoId"
    | "/projects/$projectId/sessions/new";
  id:
    | "__root__"
    | "/"
    | "/agent-progress"
    | "/agents"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/workflows"
    | "/channels/$channelId"
    | "/coding-sessions/new"
    | "/messages/new"
    | "/projects/$projectId"
    | "/shell/$sessionId"
    | "/workflows/$workflowId"
    | "/coding-sessions/$channelId/$generationId"
    | "/observe/$owner/$sessionId"
    | "/projects/$projectId/agents"
    | "/projects/$projectId/contributors"
    | "/projects/$projectId/packs"
    | "/projects/$projectId/pulse"
    | "/projects/$projectId/todos"
    | "/projects/$projectId/"
    | "/channels/$channelId/posts/$postId"
    | "/coding-sessions/$channelId/founded/$sessionRef"
    | "/projects/$projectId/code/$repoId"
    | "/projects/$projectId/sessions/new";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  agentProgressRoute: typeof agentProgressRoute;
  agentsRoute: typeof agentsRoute;
  projectsRoute: typeof projectsRoute;
  pulseRoute: typeof pulseRoute;
  remindersRoute: typeof remindersRoute;
  settingsRoute: typeof settingsRoute;
  workflowsRoute: typeof workflowsRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  codingSessionsDotnewRoute: typeof codingSessionsDotnewRoute;
  messagesDotnewRoute: typeof messagesDotnewRoute;
  projectsDotprojectIdRoute: typeof projectsDotprojectIdRouteWithChildren;
  shellDotsessionIdRoute: typeof shellDotsessionIdRoute;
  workflowsDotworkflowIdRoute: typeof workflowsDotworkflowIdRoute;
  codingSessionsDotchannelIdDotgenerationIdRoute: typeof codingSessionsDotchannelIdDotgenerationIdRoute;
  observeDotownerDotsessionIdRoute: typeof observeDotownerDotsessionIdRoute;
  channelsDotchannelIdDotpostsDotpostIdRoute: typeof channelsDotchannelIdDotpostsDotpostIdRoute;
  codingSessionsDotchannelIdDotfoundedDotsessionRefRoute: typeof codingSessionsDotchannelIdDotfoundedDotsessionRefRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflows": {
      id: "/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reminders": {
      id: "/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof remindersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pulse": {
      id: "/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof projectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agent-progress": {
      id: "/agent-progress";
      path: "/agent-progress";
      fullPath: "/agent-progress";
      preLoaderRoute: typeof agentProgressRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workflows/$workflowId": {
      id: "/workflows/$workflowId";
      path: "/workflows/$workflowId";
      fullPath: "/workflows/$workflowId";
      preLoaderRoute: typeof workflowsDotworkflowIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/shell/$sessionId": {
      id: "/shell/$sessionId";
      path: "/shell/$sessionId";
      fullPath: "/shell/$sessionId";
      preLoaderRoute: typeof shellDotsessionIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof projectsDotprojectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/new": {
      id: "/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof messagesDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/coding-sessions/new": {
      id: "/coding-sessions/new";
      path: "/coding-sessions/new";
      fullPath: "/coding-sessions/new";
      preLoaderRoute: typeof codingSessionsDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId/": {
      id: "/projects/$projectId/";
      path: "/";
      fullPath: "/projects/$projectId/";
      preLoaderRoute: typeof projectsDotprojectIdDotindexRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/projects/$projectId/todos": {
      id: "/projects/$projectId/todos";
      path: "/todos";
      fullPath: "/projects/$projectId/todos";
      preLoaderRoute: typeof projectsDotprojectIdDottodosRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/projects/$projectId/pulse": {
      id: "/projects/$projectId/pulse";
      path: "/pulse";
      fullPath: "/projects/$projectId/pulse";
      preLoaderRoute: typeof projectsDotprojectIdDotpulseRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/projects/$projectId/packs": {
      id: "/projects/$projectId/packs";
      path: "/packs";
      fullPath: "/projects/$projectId/packs";
      preLoaderRoute: typeof projectsDotprojectIdDotpacksRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/projects/$projectId/contributors": {
      id: "/projects/$projectId/contributors";
      path: "/contributors";
      fullPath: "/projects/$projectId/contributors";
      preLoaderRoute: typeof projectsDotprojectIdDotcontributorsRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/projects/$projectId/agents": {
      id: "/projects/$projectId/agents";
      path: "/agents";
      fullPath: "/projects/$projectId/agents";
      preLoaderRoute: typeof projectsDotprojectIdDotagentsRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/observe/$owner/$sessionId": {
      id: "/observe/$owner/$sessionId";
      path: "/observe/$owner/$sessionId";
      fullPath: "/observe/$owner/$sessionId";
      preLoaderRoute: typeof observeDotownerDotsessionIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/coding-sessions/$channelId/$generationId": {
      id: "/coding-sessions/$channelId/$generationId";
      path: "/coding-sessions/$channelId/$generationId";
      fullPath: "/coding-sessions/$channelId/$generationId";
      preLoaderRoute: typeof codingSessionsDotchannelIdDotgenerationIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId/sessions/new": {
      id: "/projects/$projectId/sessions/new";
      path: "/sessions/new";
      fullPath: "/projects/$projectId/sessions/new";
      preLoaderRoute: typeof projectsDotprojectIdDotsessionsDotnewRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/projects/$projectId/code/$repoId": {
      id: "/projects/$projectId/code/$repoId";
      path: "/code/$repoId";
      fullPath: "/projects/$projectId/code/$repoId";
      preLoaderRoute: typeof projectsDotprojectIdDotcodeDotrepoIdRouteImport;
      parentRoute: typeof projectsDotprojectIdRoute;
    };
    "/coding-sessions/$channelId/founded/$sessionRef": {
      id: "/coding-sessions/$channelId/founded/$sessionRef";
      path: "/coding-sessions/$channelId/founded/$sessionRef";
      fullPath: "/coding-sessions/$channelId/founded/$sessionRef";
      preLoaderRoute: typeof codingSessionsDotchannelIdDotfoundedDotsessionRefRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId/posts/$postId": {
      id: "/channels/$channelId/posts/$postId";
      path: "/channels/$channelId/posts/$postId";
      fullPath: "/channels/$channelId/posts/$postId";
      preLoaderRoute: typeof channelsDotchannelIdDotpostsDotpostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface projectsDotprojectIdRouteChildren {
  projectsDotprojectIdDotagentsRoute: typeof projectsDotprojectIdDotagentsRoute;
  projectsDotprojectIdDotcontributorsRoute: typeof projectsDotprojectIdDotcontributorsRoute;
  projectsDotprojectIdDotpacksRoute: typeof projectsDotprojectIdDotpacksRoute;
  projectsDotprojectIdDotpulseRoute: typeof projectsDotprojectIdDotpulseRoute;
  projectsDotprojectIdDottodosRoute: typeof projectsDotprojectIdDottodosRoute;
  projectsDotprojectIdDotindexRoute: typeof projectsDotprojectIdDotindexRoute;
  projectsDotprojectIdDotcodeDotrepoIdRoute: typeof projectsDotprojectIdDotcodeDotrepoIdRoute;
  projectsDotprojectIdDotsessionsDotnewRoute: typeof projectsDotprojectIdDotsessionsDotnewRoute;
}

const projectsDotprojectIdRouteChildren: projectsDotprojectIdRouteChildren = {
  projectsDotprojectIdDotagentsRoute: projectsDotprojectIdDotagentsRoute,
  projectsDotprojectIdDotcontributorsRoute:
    projectsDotprojectIdDotcontributorsRoute,
  projectsDotprojectIdDotpacksRoute: projectsDotprojectIdDotpacksRoute,
  projectsDotprojectIdDotpulseRoute: projectsDotprojectIdDotpulseRoute,
  projectsDotprojectIdDottodosRoute: projectsDotprojectIdDottodosRoute,
  projectsDotprojectIdDotindexRoute: projectsDotprojectIdDotindexRoute,
  projectsDotprojectIdDotcodeDotrepoIdRoute:
    projectsDotprojectIdDotcodeDotrepoIdRoute,
  projectsDotprojectIdDotsessionsDotnewRoute:
    projectsDotprojectIdDotsessionsDotnewRoute,
};

const projectsDotprojectIdRouteWithChildren =
  projectsDotprojectIdRoute._addFileChildren(projectsDotprojectIdRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  agentProgressRoute: agentProgressRoute,
  agentsRoute: agentsRoute,
  projectsRoute: projectsRoute,
  pulseRoute: pulseRoute,
  remindersRoute: remindersRoute,
  settingsRoute: settingsRoute,
  workflowsRoute: workflowsRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  codingSessionsDotnewRoute: codingSessionsDotnewRoute,
  messagesDotnewRoute: messagesDotnewRoute,
  projectsDotprojectIdRoute: projectsDotprojectIdRouteWithChildren,
  shellDotsessionIdRoute: shellDotsessionIdRoute,
  workflowsDotworkflowIdRoute: workflowsDotworkflowIdRoute,
  codingSessionsDotchannelIdDotgenerationIdRoute:
    codingSessionsDotchannelIdDotgenerationIdRoute,
  observeDotownerDotsessionIdRoute: observeDotownerDotsessionIdRoute,
  channelsDotchannelIdDotpostsDotpostIdRoute:
    channelsDotchannelIdDotpostsDotpostIdRoute,
  codingSessionsDotchannelIdDotfoundedDotsessionRefRoute:
    codingSessionsDotchannelIdDotfoundedDotsessionRefRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
