import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { expect, type Locator, type Page } from "@playwright/test";

import { waitForAnimations } from "../../helpers/animations";

/**
 * Shared machinery for the Project Pulse missions spec.
 *
 * Two things live here rather than in the spec: the seam that answers
 * `pulse_mission_rows` with the frozen contract, and the screenshot bookkeeping
 * that refuses to write two identical PNGs.
 */

const here = dirname(fileURLToPath(import.meta.url));

/** Where the screenshots for this lane land. */
// These land in the repo's own `test-results/`, like every other spec's
// shots. The absolute path this replaced was a review directory on one
// laptop, so the whole file errored `ENOENT`/`EACCES` for anyone else and
// the evidence it claims to produce existed on exactly one machine.
export const PULSE_MISSION_SHOT_DIR = "test-results/pulse-missions";

/** The two widths every shot is taken at. */
export const PULSE_MISSION_VIEWPORTS = [
  { width: 1280, height: 720 },
  { width: 1920, height: 1080 },
] as const;

/**
 * The frozen contract, read from the same file the unit tests decode.
 *
 * Never hand-edited here: it is generated by
 * `crates/beekeeper-core/src/pulse_mission_tests.rs`, and a spec that adjusted it
 * would be testing this spec's idea of the wire rather than Rust's.
 */
export function pulseMissionFixture(): Record<string, unknown> {
  return JSON.parse(
    readFileSync(
      resolve(
        here,
        "../../../src/features/project-pulse/lib/pulseMissionResponse.fixture.json",
      ),
      "utf8",
    ),
  );
}

/**
 * The same rows as a surface with **no identity** renders them.
 *
 * Generated by `crates/beekeeper-core/src/pulse_mission_fixture_tests.rs` from the
 * same renderer, so the "we cannot say what waits on you" sentence is the one
 * Rust composes. The spec used to push that line into the fixture by hand,
 * which proved the component and not the model (REVIEW-L9 §6).
 */
export function pulseMissionNoIdentityFixture(): Record<string, unknown> {
  return JSON.parse(
    readFileSync(
      resolve(
        here,
        "../../../src/features/project-pulse/lib/pulseMissionNoIdentity.fixture.json",
      ),
      "utf8",
    ),
  ) as Record<string, unknown>;
}

/**
 * Answer `pulse_mission_rows` with a payload, leaving every other command to
 * the mock bridge.
 *
 * The bridge's own command switch lives in `src/testing/e2eBridge.ts`, which
 * this lane does not own, so the seam is installed from the spec instead: an
 * accessor on `window.__TAURI_INTERNALS__` that wraps whatever `mockIPC`
 * assigns as `invoke`. Must be registered **before** `installMockBridge`,
 * because the bridge installs at app mount and the trap has to be in place
 * when it does.
 */
export async function mockPulseMissionRows(
  page: Page,
  payload: unknown,
): Promise<void> {
  await page.addInitScript((fixture) => {
    type Internals = Record<string, unknown> & { invoke?: unknown };
    let internals: Internals | undefined;
    const wrap = (target: Internals) => {
      if (!target || Object.hasOwn(target, "__pulseMissionWrapped")) return;
      let inner:
        | ((command: string, args?: unknown, options?: unknown) => unknown)
        | undefined;
      Object.defineProperty(target, "invoke", {
        configurable: true,
        get:
          () => async (command: string, args?: unknown, options?: unknown) => {
            if (command === "pulse_mission_rows") {
              return structuredClone(fixture);
            }
            if (!inner) {
              throw new Error(`no mocked Tauri command: ${command}`);
            }
            return inner(command, args, options);
          },
        set: (next) => {
          inner = next as typeof inner;
        },
      });
      Object.defineProperty(target, "__pulseMissionWrapped", { value: true });
    };
    Object.defineProperty(window, "__TAURI_INTERNALS__", {
      configurable: true,
      get: () => internals,
      set: (value: Internals) => {
        internals = value;
        wrap(value);
      },
    });
  }, payload as never);
}

const digests = new Map<string, Map<string, string>>();

/**
 * Capture one scoped shot at both widths, refusing a duplicate subject.
 *
 * Two byte-identical PNGs of *different subjects* mean the spec photographed
 * the same state twice and labelled them differently, which is worse than
 * having no screenshot: a reviewer reads the caption and believes the pixels.
 * That is refused outright, per viewport.
 *
 * The same subject at two widths is deliberately **not** refused, and the two
 * files are byte-identical. The Pulse content column is width-capped, so a
 * scoped shot of a card is the same pixels at 1280 and at 1920 — a true fact
 * about the layout. Two alternatives were tried and are worse: jittering the
 * capture manufactures a difference that hides it, and photographing the whole
 * viewport at 1920 makes *different subjects* collide instead, because the
 * whole screen is the same for all six (the guard below caught exactly that).
 * The honest reading of these twelve files is six subjects, each shown to be
 * identical at both widths.
 */
export async function capturePulseMissionShot(
  page: Page,
  locator: Locator,
  name: string,
): Promise<void> {
  for (const viewport of PULSE_MISSION_VIEWPORTS) {
    await page.setViewportSize(viewport);
    await expect(locator).toBeVisible();
    await waitForAnimations(page);
    const label = `${name}-${viewport.width}x${viewport.height}`;
    const buffer = await locator.screenshot({
      path: `${PULSE_MISSION_SHOT_DIR}/${label}.png`,
    });
    const digest = createHash("sha256").update(buffer).digest("hex");
    const bucketKey = `${viewport.width}x${viewport.height}`;
    const bucket = digests.get(bucketKey) ?? new Map<string, string>();
    for (const [other, otherDigest] of bucket) {
      expect(digest, `${label} captured the same pixels as ${other}`).not.toBe(
        otherDigest,
      );
    }
    bucket.set(label, digest);
    digests.set(bucketKey, bucket);
  }
  await page.setViewportSize({
    width: PULSE_MISSION_VIEWPORTS[0].width,
    height: PULSE_MISSION_VIEWPORTS[0].height,
  });
}

/** The mission row for one session key. */
export function missionRow(page: Page, sessionKey: string): Locator {
  return page.getByTestId(`pulse-mission-row-${sessionKey}`);
}
