/**
 * Marking a host's own words, and deciding whether they still need to be a
 * turn.
 *
 * Split out for {@link discloseCodingSessionHire} and its refusal callers in
 * `codingSessionHireDisclosure.ts` (ledger 178(b)): a hire that this computer
 * refused, or otherwise answered on the founder's behalf, is disclosed twice —
 * once as a turn addressed to the requesting seat, once as a line in the
 * umbrella. Neither is a person's words, and one of the two used to be
 * indistinguishable from a person's turn on the wire.
 *
 * On 2026-09-20 that cost a real turn: the founder's Desktop answered a
 * routed hire's `HIRE_NO_ROUTE` in about a second, `bee sessions hire`'s own
 * poll read the refusal and returned it to the lead, and the lead retried
 * successfully ten seconds later. The same refusal, addressed to the lead's
 * own live seat as a `thread.turn.start`, sat in the provider's mailbox and
 * was delivered as a fresh turn 43 seconds after publish — well after the
 * retry — and the lead spent 84.9s and 580,779 input tokens ($0.59)
 * concluding "You're pointing at the refusal from the routed hire" about a
 * message Brian never sent (finding 178(b),
 * `docs/history/2026-09-20-astra-kettle-audit.md` § 4.A).
 */

/** What every host-authored disclosure is marked with, verbatim. */
export const CODING_SESSION_HOST_NOTICE_MARKER = "Host notice — not a person";

/**
 * Mark the umbrella's own line for a host disclosure.
 *
 * A plain prefix: the umbrella notice is an ordinary lane message nothing
 * parses structurally (`codingSessionHireRefusalNotice` and its siblings are
 * read by people, not by `bee sessions hire`), so the marker can sit at the
 * very front where a reader sees it first.
 */
export function markCodingSessionHostNoticeText(text: string): string {
  const bracket = `[${CODING_SESSION_HOST_NOTICE_MARKER}]`;
  return text.startsWith(bracket) ? text : `${bracket} ${text}`;
}

/**
 * Mark the text a host disclosure sends as a turn, without disturbing its
 * front.
 *
 * The turn text cannot take the marker as a prefix the way the notice does.
 * `bee sessions hire` recognizes a refusal *structurally*, by the text
 * starting with the exact `hire refused: ` prefix
 * (`HIRE_REFUSAL_PREFIX`/`parse_hire_refusal`,
 * `crates/buzz-core/src/coding_session_lifecycle_command.rs`,
 * `crates/buzz-cli/src/commands/sessions/crew.rs`) — its own test fixes this
 * ("`please hire refused: HIRE_OFF — x`, // prefix must start the text").
 * Putting anything ahead of that prefix would make the CLI unable to parse
 * any refusal ever again, turning every refused hire back into the
 * `unconfirmed` one ledger 169 fixed. The marker goes at the end instead: a
 * reader — model or person — still sees the whole turn before acting on it,
 * and the structural prefix `bee sessions hire` depends on is untouched.
 */
export function markCodingSessionHostTurnText(text: string): string {
  const suffix = `[${CODING_SESSION_HOST_NOTICE_MARKER}: generated by this computer's host process, never typed by an operator]`;
  return text.endsWith(suffix) ? text : `${text} ${suffix}`;
}

/**
 * How long `bee sessions hire`'s own wait may still be open when this host
 * answers, in seconds.
 *
 * Matches `HIRE_WAIT_SECONDS` in
 * `crates/buzz-cli/src/commands/sessions/crew.rs` (asserted there at 120 by
 * `crew_tests.rs`) and {@link CODING_SESSION_HIRE_MAX_AGE_SECONDS}'s own note
 * on the same number in `codingSessionHireAnswer.ts`. Kept as a separate
 * constant rather than imported, because the two live in different
 * languages; a drift between them is a fact for `crew_tests.rs`'s own
 * assertion to catch, not something this module can enforce.
 */
export const CODING_SESSION_HIRE_ANSWER_SYNCHRONOUS_SECONDS = 120;

/**
 * Could the requester's own `bee sessions hire` still be polling for this
 * answer, or has it already reported `unconfirmed` and moved on?
 *
 * `bee sessions hire` polls the relay directly for up to `HIRE_WAIT_SECONDS`
 * after the request it sent, reading a refusal the same way this host
 * answers one — off the raw 44220 its own poll finds. Within that window, a
 * *turn* addressed at the same live seat carries nothing the requester does
 * not already have: it is the very answer the CLI just read, arriving a
 * second time whenever the provider's mailbox next delivers it — which may
 * be tens of seconds later, once the requester has moved on, and reads as
 * fresh, unprompted instruction (ledger 178(b)). Outside the window the CLI
 * has already given up and told its caller `unconfirmed`; a turn is the only
 * way left to tell the requester what actually happened.
 */
export function codingSessionHireAnswerWithinRequesterWindow(input: {
  /** The hire request's own `created_at`, Unix seconds. */
  requestCreatedAt: number;
  /** This host's clock at the moment it is ready to answer, Unix seconds. */
  nowSeconds: number;
  /** Override for tests. Defaults to the CLI's own wait. */
  maxAgeSeconds?: number;
}): boolean {
  const maxAge =
    input.maxAgeSeconds ?? CODING_SESSION_HIRE_ANSWER_SYNCHRONOUS_SECONDS;
  return input.nowSeconds - input.requestCreatedAt <= maxAge;
}
