import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import {
  CODING_SESSION_LAND_NOT_RUN_SENTENCE,
  codingSessionMissionLandModel,
  decodeCodingSessionLandResult,
} from "./codingSessionMissionLand.ts";

/** The `coding_session_land` adapter's own output, generated by its Rust test. */
const FIXTURE = JSON.parse(
  readFileSync(
    new URL("./codingSessionLandAdapterResponse.fixture.json", import.meta.url),
    "utf8",
  ),
);

const resolveWho = (pubkey) =>
  pubkey === FIXTURE.admitted.evidence.dispositionAuthorPubkey
    ? "the founder"
    : pubkey.slice(0, 8);

test("L8.2: every state of the adapter's real output decodes", () => {
  for (const key of ["admitted", "refused", "ungoverned", "unknown"]) {
    const result = decodeCodingSessionLandResult(FIXTURE[key]);
    assert.equal(result.implementation, "buzz-core");
  }
});

test("L8.2: a decoder that loses a key is a loud failure", () => {
  const { newestVerdict, ...missing } = FIXTURE.admitted;
  assert.ok(newestVerdict);
  assert.throws(
    () => decodeCodingSessionLandResult(missing),
    /malformed response/,
  );
});

test("L8.2: an admitted commit offers the command, and the command names the commit", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.admitted),
    resolveWho,
  });
  const sha = FIXTURE.admitted.evidence.headSha;
  assert.equal(model.state, "ready");
  assert.equal(model.buttonLabel, `Land ${sha.slice(0, 7)} on main`);
  assert.equal(model.command, `git push origin ${sha}:refs/heads/main`);
  // A branch name is not a commit: the command must never carry one.
  assert.ok(!/refs\/heads\/main:refs/.test(model.command));
  assert.equal(
    model.approvalSentence,
    `Approved by the founder in disposition ${FIXTURE.admitted.evidence.dispositionEventId.slice(0, 8)}, over report ${FIXTURE.admitted.evidence.reportEventId.slice(0, 8)}. The relay's require-verdict rule admits this commit on refs/heads/main.`,
  );
  assert.equal(model.notRunSentence, CODING_SESSION_LAND_NOT_RUN_SENTENCE);
  assert.match(model.notRunSentence, /irreversible/);
  assert.match(model.notRunSentence, /holds no checkout/);
  assert.match(model.notRunSentence, /credential lives in your shell/);
});

test("L8.2: a refusal prints §1j's string verbatim behind §1l's prefix", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.refused),
    resolveWho,
  });
  assert.equal(model.state, "refused");
  assert.equal(model.command, null);
  assert.equal(
    model.sentence,
    `Not ready to land: ${FIXTURE.refused.refusalReason}`,
  );
  assert.match(
    model.sentence,
    /require-verdict is set and no mission verdict names this commit/,
  );
});

test("L8.2: an ungoverned repository says so and still shows the verdict it read", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.ungoverned),
    resolveWho,
  });
  assert.equal(model.state, "ungoverned");
  assert.equal(model.command, null);
  assert.equal(
    model.sentence,
    `This repository has no require-verdict rule, so nothing here gates the push. The mission's newest verdict is approve by the founder over report ${FIXTURE.ungoverned.newestVerdict.reportEventId.slice(0, 8)}.`,
  );
});

test("L8.2: no repository record is unknown, never 'no rule', and says which fact it is", () => {
  const noRepoRef = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.unknown),
    repositoryUnknownReason: "no-repo-ref",
    resolveWho,
  });
  assert.equal(noRepoRef.state, "unknown");
  assert.equal(
    noRepoRef.sentence,
    "This session's creates name no repository, so nothing here can say what gates a push.",
  );

  // A named repository whose announcement did not reach this view is a
  // different fact, and "not read" is the honest word for it — never "no rule".
  const notRead = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.unknown),
    repositoryUnknownReason: "not-read",
    resolveWho,
  });
  assert.equal(notRead.state, "unknown");
  assert.equal(
    notRead.sentence,
    "The repository this session names was not read here, so nothing can say what gates a push.",
  );
  for (const model of [noRepoRef, notRead]) {
    assert.notEqual(model.state, "ungoverned");
    assert.ok(!/no require-verdict rule/.test(model.sentence));
  }
});

test("L8.2: an approval scoped to another branch is refused, with §1j's own words", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.approvedForAnotherRef),
    resolveWho,
  });
  assert.equal(model.state, "refused");
  assert.equal(model.command, null);
  assert.equal(
    model.sentence,
    `Not ready to land: ${FIXTURE.approvedForAnotherRef.refusalReason}`,
  );
  assert.match(
    model.sentence,
    /is approved for release, and this is a different ref\. A verdict admits a commit to the branch its report named\./,
  );
});

test("L8.2: §1j's no-verdict string discloses both caps", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.refused),
    resolveWho,
  });
  // REVIEW-L8 F2: fix round 1 shipped this sentence without either bound.
  assert.match(model.sentence, /the newest 16 on this channel/);
  assert.match(model.sentence, /newest 512 team transactions/);
  assert.match(model.sentence, /An older ruling can fall outside both\./);
});
