import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import {
  CODING_SESSION_POLICY_ENFORCED_FIELDS,
  CODING_SESSION_POLICY_STATED_NOT_ENFORCED,
  EMPTY_CODING_SESSION_POLICY_DRAFT,
  codingSessionPolicyContent,
  codingSessionPolicyDraftSetsAnything,
  codingSessionPolicyFacts,
  decodeCodingSessionPolicyBuildResult,
  decodeCodingSessionPolicyReadResult,
  decodeCodingSessionPolicyRecord,
} from "./codingSessionPolicy.ts";

// Generated by the Rust adapter itself, not by hand:
// `the_typescript_decoder_fixture_is_this_adapter_s_real_output` in
// desktop/src-tauri/src/commands/coding_session_policy_tests.rs writes this
// file, and that test fails if it goes stale. A hand-written fixture is what
// let the team-fold decoder stay green while it would have thrown for every
// real session (REVIEW-B1c B1); this decoder is pinned to real output so the
// same trap cannot open twice.
const FIXTURE = JSON.parse(
  readFileSync(
    resolve(
      dirname(fileURLToPath(import.meta.url)),
      "codingSessionPolicyAdapterResponse.fixture.json",
    ),
    "utf8",
  ),
);

test("the decoder accepts the adapter's own build response", () => {
  const decoded = decodeCodingSessionPolicyBuildResult(FIXTURE.build);
  assert.equal(decoded.schema, "buzz-coding-session-policy-adapter/v1");
  assert.equal(decoded.implementation, "buzz-core");
  // The kind integer comes from buzz-core's allocation. Nothing in TypeScript
  // writes 44245.
  assert.equal(decoded.kind, 44245);
  assert.deepEqual(
    decoded.tags.map((tag) => tag[0]),
    ["h", "d", "csp-v", "csp-genesis"],
  );
  assert.equal(decoded.record.posture, "overnight");
  assert.equal(decoded.record.budget.turns, 240);
  assert.equal(decoded.record.setsAnyPolicy, true);
});

test("the decoder accepts the adapter's own read response", () => {
  const decoded = decodeCodingSessionPolicyReadResult(FIXTURE.read);
  assert.equal(decoded.eventId.length, 64);
  assert.equal(decoded.authorPubkey.length, 64);
  assert.equal(decoded.createdAt, 1_800_000_000);
  // One flattener in Rust, so a draft and the signed thing it became read the
  // same on both boundaries.
  assert.deepEqual(decoded.record, FIXTURE.build.record);
});

test("the withdrawal record decodes and says it sets nothing", () => {
  const decoded = decodeCodingSessionPolicyBuildResult(FIXTURE.withdrawal);
  assert.equal(decoded.record.setsAnyPolicy, false);
  // Present and null, never absent: "no policy" and "this build does not
  // disclose budgets" must not look the same.
  assert.equal(decoded.record.budget, null);
  assert.equal(decoded.record.posture, null);
  assert.deepEqual(codingSessionPolicyFacts(decoded.record), []);
});

test("the record carries exactly the adapter's key set", () => {
  assert.deepEqual(Object.keys(FIXTURE.build.record).sort(), [
    "attention",
    "bench",
    "budget",
    "gates",
    "genesisRef",
    "irreversible",
    "posture",
    "sessionRef",
    "setsAnyPolicy",
    "stop",
  ]);
});

test("a record missing any disclosure key is refused", () => {
  for (const key of Object.keys(FIXTURE.build.record)) {
    const damaged = { ...FIXTURE.build.record };
    delete damaged[key];
    assert.throws(
      () => decodeCodingSessionPolicyRecord(damaged),
      /malformed record/,
      `dropping ${key} must be a loud failure, not an unset field`,
    );
  }
});

test("an unanswered question becomes an absent key, never an explicit null", () => {
  const content = codingSessionPolicyContent({
    draft: { ...EMPTY_CODING_SESSION_POLICY_DRAFT, posture: "ship" },
    sessionRef: "5b7e1c2a-90d4-4b0e-a1f3-7c2d8e6f4a10",
    genesisRef: "12".repeat(32),
  });
  assert.deepEqual(Object.keys(content).sort(), [
    "genesisRef",
    "posture",
    "schema",
    "sessionRef",
  ]);
  assert.equal(JSON.stringify(content).includes("null"), false);
});

test("an empty collection is omitted rather than sent as an empty sub-object", () => {
  // `"bench": {"identities": []}` is refused by the decoder — the way to say
  // "bench nobody" is to omit the key — so a group nobody answered never
  // reaches the boundary at all.
  const content = codingSessionPolicyContent({
    draft: {
      ...EMPTY_CODING_SESSION_POLICY_DRAFT,
      benchIdentities: [],
      benchProviders: [],
      requiredGates: [],
      irreversible: [],
    },
    sessionRef: "5b7e1c2a-90d4-4b0e-a1f3-7c2d8e6f4a10",
    genesisRef: "12".repeat(32),
  });
  assert.equal(Object.hasOwn(content, "bench"), false);
  assert.equal(Object.hasOwn(content, "gates"), false);
  assert.equal(Object.hasOwn(content, "irreversible"), false);
  assert.equal(
    codingSessionPolicyDraftSetsAnything(EMPTY_CODING_SESSION_POLICY_DRAFT),
    false,
  );
});

test("only fields the record sets become facts, and exactly one is enforced", () => {
  const facts = codingSessionPolicyFacts(FIXTURE.build.record);
  const fields = facts.map((fact) => fact.field);
  assert.ok(fields.includes("budget.turns"));
  assert.ok(fields.includes("irreversible"));
  // POLICY.md §4: `budget.turns` and nothing else. Lane B2.4 shipped its
  // consumer (the provider's turn gate); this list is the only place the
  // claim is made, so it is asserted exactly rather than by length.
  assert.deepEqual(CODING_SESSION_POLICY_ENFORCED_FIELDS, ["budget.turns"]);
  assert.equal(
    facts.find((fact) => fact.field === "budget.turns")?.enforced,
    true,
  );
  assert.equal(
    facts
      .filter((fact) => fact.field !== "budget.turns")
      .every((fact) => fact.enforced === false),
    true,
  );
  // POLICY.md §4.2's own words, so the disclosure and the contract cannot
  // soften independently of each other — and the one enforced field is named
  // rather than buried under a blanket "nothing is enforced".
  assert.match(
    CODING_SESSION_POLICY_STATED_NOT_ENFORCED,
    /read and shown, and nothing checks them/,
  );
  assert.match(
    CODING_SESSION_POLICY_STATED_NOT_ENFORCED,
    /a stated intention, not an enforced limit/,
  );
  assert.match(
    CODING_SESSION_POLICY_STATED_NOT_ENFORCED,
    /the provider refuses a turn once a session has spent it/,
  );
});
