import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import test from "node:test";

import {
  CODING_SESSION_OBSERVATION_FOLD_RESPONSE_SCHEMA,
  decodeCodingSessionObservationFold,
} from "./codingSessionObservationWire.ts";

// **Generated by the Rust adapter**, not by hand. B1c's own defect is why:
// hand-written fixtures kept `pnpm test` green while the decoder would have
// thrown for every real session. The Rust test
// `the_typescript_decoder_fixture_is_this_adapter_s_real_output` regenerates
// this file and fails when it differs, so a field the adapter renames and this
// decoder does not is a failing Rust test rather than a silently empty card.
const FIXTURE = JSON.parse(
  readFileSync(
    fileURLToPath(
      new URL(
        "./codingSessionObservationFoldAdapterResponse.fixture.json",
        import.meta.url,
      ),
    ),
    "utf8",
  ),
);

function clone() {
  return structuredClone(FIXTURE);
}

test("the adapter's own output decodes, field for field", () => {
  const fold = decodeCodingSessionObservationFold(clone());

  assert.equal(fold.schema, CODING_SESSION_OBSERVATION_FOLD_RESPONSE_SCHEMA);
  assert.equal(fold.implementation, "buzz-core");
  assert.equal(fold.checkpoints.length, 1);
  assert.equal(fold.findings.length, 1);
  assert.equal(fold.phases.length, 1);
  assert.equal(fold.unresolved.length, 1);
  assert.deepEqual(fold.ignored, []);

  // The two halves of the 2026-09-02 addendum, on the wire and decoded apart.
  assert.equal(fold.gates.length, 2);
  const observed = fold.gates.find((row) => row.source === "observed");
  const declared = fold.gates.find((row) => row.source === "declared");
  assert.equal(observed.outcome, "failed");
  assert.equal(declared.outcome, "passed");
  assert.equal(observed.command, "cargo test -p buzz-cli");
  assert.equal(declared.command, "cargo test -p buzz-cli");
  assert.notEqual(observed.authorPubkey, declared.authorPubkey);

  // Every truncation count is present, including the zeroes: "nothing dropped"
  // and "this build does not count" must never look alike.
  assert.deepEqual(fold.truncated, {
    checkpoints: 0,
    gates: 0,
    findings: 0,
    phases: 0,
    unresolved: 0,
    ignored: 0,
    misclaimedObserved: 0,
    entryEventIds: 0,
    displacedGates: 0,
    displacedFindings: 0,
  });
  // REVIEW-L5 F2: this fixture's caller resolved the provider set, so the
  // provider's `observed` row is honoured and nothing is misclaimed.
  assert.equal(fold.provenanceChecked, true);
  assert.deepEqual(fold.misclaimedObserved, []);
  assert.match(fold.disclosure, /settles nothing/);
});

test("one extra key is refused, and the refusal names it", () => {
  const response = clone();
  response.gates[0].exitCode = 0;
  assert.throws(
    () => decodeCodingSessionObservationFold(response),
    /gates\[0\] carries unsupported "exitCode"/,
  );

  const topLevel = clone();
  topLevel.summary = "everything is fine";
  assert.throws(
    () => decodeCodingSessionObservationFold(topLevel),
    /response carries unsupported "summary"/,
  );
});

test("one missing key is refused, and the refusal names it", () => {
  const response = clone();
  delete response.gates[0].source;
  assert.throws(
    () => decodeCodingSessionObservationFold(response),
    /gates\[0\] is missing "source"/,
  );

  const topLevel = clone();
  delete topLevel.truncated;
  assert.throws(
    () => decodeCodingSessionObservationFold(topLevel),
    /response is missing "truncated"/,
  );
});

test("a null where a value is required is refused, and named", () => {
  const outcome = clone();
  outcome.gates[0].outcome = null;
  assert.throws(
    () => decodeCodingSessionObservationFold(outcome),
    /gates\[0\] field "outcome" must be one of/,
  );

  const command = clone();
  command.gates[0].command = null;
  assert.throws(
    () => decodeCodingSessionObservationFold(command),
    /gates\[0\] field "command" must be a non-empty string/,
  );

  const dropped = clone();
  dropped.truncated.gates = null;
  assert.throws(
    () => decodeCodingSessionObservationFold(dropped),
    /truncated field "gates" must be a non-negative integer/,
  );
});

test("a token outside a closed vocabulary is refused with the whole set", () => {
  const source = clone();
  source.gates[0].source = "inferred";
  assert.throws(
    () => decodeCodingSessionObservationFold(source),
    /gates\[0\] field "source" must be one of "observed", "declared"/,
  );

  const phase = clone();
  phase.checkpoints[0].phase = "review";
  assert.throws(
    () => decodeCodingSessionObservationFold(phase),
    /checkpoints\[0\] field "phase" must be one of/,
  );
});

test("an unset optional decodes as null, never as absent", () => {
  const fold = decodeCodingSessionObservationFold(clone());
  assert.equal(fold.checkpoints[0].note, null);
  assert.equal(fold.findings[0].decisionRef, null);
  assert.ok("note" in fold.checkpoints[0]);
  assert.ok("decisionRef" in fold.findings[0]);
});

test("a truncated count renders as truncation, not as absence", () => {
  const response = clone();
  response.truncated.gates = 7;
  response.truncated.entryEventIds = 3;
  const fold = decodeCodingSessionObservationFold(response);
  assert.equal(fold.truncated.gates, 7);
  assert.equal(fold.truncated.entryEventIds, 3);
});

test("an ignored entry is decoded, never dropped", () => {
  const response = clone();
  response.ignored.push({
    eventId: "ab".repeat(32),
    reason: "invalid observation signature: bad",
  });
  const fold = decodeCodingSessionObservationFold(response);
  assert.equal(fold.ignored.length, 1);
  assert.match(fold.ignored[0].reason, /invalid observation signature/);
});

test("a foreign adapter schema is refused", () => {
  const response = clone();
  response.schema = "buzz-coding-session-team-fold-adapter/v1";
  assert.throws(
    () => decodeCodingSessionObservationFold(response),
    /response field "schema" must be/,
  );
});

test("REVIEW-L5 F2: provenanceChecked is required, and must be a boolean", () => {
  const missing = clone();
  delete missing.provenanceChecked;
  assert.throws(
    () => decodeCodingSessionObservationFold(missing),
    /response is missing "provenanceChecked"/,
  );

  const wrong = clone();
  wrong.provenanceChecked = "yes";
  assert.throws(
    () => decodeCodingSessionObservationFold(wrong),
    /response field "provenanceChecked" must be a boolean/,
  );
});

test("REVIEW-L5 F1: the displacement counts are required too", () => {
  for (const key of ["displacedGates", "displacedFindings"]) {
    const response = clone();
    delete response.truncated[key];
    assert.throws(
      () => decodeCodingSessionObservationFold(response),
      new RegExp(`truncated is missing "${key}"`),
    );
  }
});
