/**
 * Marking a host's own words so they are never mistaken for a person's.
 *
 * Split out for {@link discloseCodingSessionHire} in
 * `codingSessionHireDisclosure.ts` (ledger 178(b)): a hire that this computer
 * refused, or otherwise answered on the founder's behalf, is disclosed twice —
 * once as a turn addressed to the requesting seat, once as a line in the
 * umbrella. Neither is a person's words, and one of the two used to be
 * indistinguishable from a person's turn on the wire.
 *
 * On 2026-09-20 that cost a real turn: the founder's Desktop answered a
 * routed hire's `HIRE_NO_ROUTE` in about a second, `bee sessions hire`'s own
 * poll read the refusal and returned it to the lead, and the lead retried
 * successfully ten seconds later. The same refusal, addressed to the lead's
 * own live seat as a `thread.turn.start`, sat in the provider's mailbox and
 * was delivered as a fresh turn 43 seconds after publish — well after the
 * retry — and the lead spent 84.9s and 580,779 input tokens ($0.59)
 * concluding "You're pointing at the refusal from the routed hire" about a
 * message Brian never sent (finding 178(b),
 * `docs/history/2026-09-20-astra-kettle-audit.md` § 4.A).
 *
 * The fix is not to stop publishing that turn — `bee sessions hire` reads the
 * very same event directly off the relay to answer its own poll
 * (`find_hire_refusal`/`wait_for_hire`,
 * `crates/buzz-cli/src/commands/sessions/crew.rs`), so it is the CLI's
 * *answer channel*, and suppressing it would turn every fast refusal into an
 * `unconfirmed` one (ledger 169). Two other things fix it instead: the text
 * here, and the `hostAnswer` wire tag
 * (`CODING_SESSION_HOST_ANSWER_TAG_NAME`, `codingSessionCommand.ts`) that
 * tells a provider's turn intake to record the answer without ever opening a
 * turn from it.
 */

/** What every host-authored disclosure is marked with, verbatim. */
export const CODING_SESSION_HOST_NOTICE_MARKER = "Host notice — not a person";

/**
 * Mark the umbrella's own line for a host disclosure.
 *
 * A plain prefix: the umbrella notice is an ordinary lane message nothing
 * parses structurally (`codingSessionHireRefusalNotice` and its siblings are
 * read by people, not by `bee sessions hire`), so the marker can sit at the
 * very front where a reader sees it first.
 */
export function markCodingSessionHostNoticeText(text: string): string {
  const bracket = `[${CODING_SESSION_HOST_NOTICE_MARKER}]`;
  return text.startsWith(bracket) ? text : `${bracket} ${text}`;
}

/**
 * Mark the text a host disclosure sends as a turn, without disturbing its
 * front.
 *
 * The turn text cannot take the marker as a prefix the way the notice does.
 * `bee sessions hire` recognizes a refusal *structurally*, by the text
 * starting with the exact `hire refused: ` prefix
 * (`HIRE_REFUSAL_PREFIX`/`parse_hire_refusal`,
 * `crates/buzz-core/src/coding_session_lifecycle_command.rs`,
 * `crates/buzz-cli/src/commands/sessions/crew.rs`) — its own test fixes this
 * ("`please hire refused: HIRE_OFF — x`, // prefix must start the text").
 * Putting anything ahead of that prefix would make the CLI unable to parse
 * any refusal ever again, turning every refused hire back into the
 * `unconfirmed` one ledger 169 fixed. The marker goes at the end instead: a
 * reader — model or person — still sees the whole turn before acting on it,
 * and the structural prefix `bee sessions hire` depends on is untouched.
 */
export function markCodingSessionHostTurnText(text: string): string {
  const suffix = `[${CODING_SESSION_HOST_NOTICE_MARKER}: generated by this computer's host process, never typed by an operator]`;
  return text.endsWith(suffix) ? text : `${text} ${suffix}`;
}

/**
 * Appended to the umbrella notice when this host's tagged answer turn was
 * refused by an older relay and republished untagged (ledger 192).
 *
 * That relay's ingest allowlist predates `buzz-host-answer` (lane 181), so
 * `discloseCodingSessionHire`'s fallback drops the tag rather than leaving
 * the requester unanswered — see
 * {@link isCodingSessionHostAnswerTagUnsupportedRejection} in
 * `codingSessionCommand.ts`. Untagged, the requesting seat's provider treats
 * the turn as an ordinary one and opens a turn for it instead of recording it
 * silently; this sentence is the only place a person sees that trade was
 * made.
 */
export const CODING_SESSION_HOST_ANSWER_DOWNGRADE_NOTE =
  "This relay does not yet know the host-answer tag, so this answer was sent untagged — the requesting seat's provider will open a turn for it rather than recording it silently.";
