import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import {
  CODING_SESSION_LAND_NO_GATE_ROWS_READ,
  CODING_SESSION_LAND_NOT_RUN_SENTENCE,
  codingSessionMissionLandModel,
  decodeCodingSessionLandResult,
} from "./codingSessionMissionLand.ts";

/** The `coding_session_land` adapter's own output, generated by its Rust test. */
const FIXTURE = JSON.parse(
  readFileSync(
    new URL("./codingSessionLandAdapterResponse.fixture.json", import.meta.url),
    "utf8",
  ),
);

const resolveWho = (pubkey) =>
  pubkey === FIXTURE.admitted.evidence.dispositionAuthorPubkey
    ? "the founder"
    : pubkey.slice(0, 8);

test("L8.2: every state of the adapter's real output decodes", () => {
  for (const key of [
    "admitted",
    "observedGates",
    "verifiedButGatesNotGreen",
    "refused",
    "ungoverned",
    "unknown",
  ]) {
    const result = decodeCodingSessionLandResult(FIXTURE[key]);
    assert.equal(result.implementation, "buzz-core");
  }
});

test("L8.2: a decoder that loses a key is a loud failure", () => {
  const { newestVerdict, ...missing } = FIXTURE.admitted;
  assert.ok(newestVerdict);
  assert.throws(
    () => decodeCodingSessionLandResult(missing),
    /malformed response/,
  );
});

test("L8.2: an admitted commit offers the command, and the command names the commit", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.admitted),
    resolveWho,
  });
  const sha = FIXTURE.admitted.evidence.headSha;
  assert.equal(model.state, "ready");
  assert.equal(model.buttonLabel, `Land ${sha.slice(0, 7)} on main`);
  assert.equal(model.command, `git push origin ${sha}:refs/heads/main`);
  // A branch name is not a commit: the command must never carry one.
  assert.ok(!/refs\/heads\/main:refs/.test(model.command));
  assert.equal(
    model.approvalSentence,
    `Approved by the founder in disposition ${FIXTURE.admitted.evidence.dispositionEventId.slice(0, 8)}, over report ${FIXTURE.admitted.evidence.reportEventId.slice(0, 8)}, and ${FIXTURE.admitted.evidence.verifierPubkey.slice(0, 8)} did not refute it (refutation ${FIXTURE.admitted.evidence.refutationEventId.slice(0, 8)}), over ${FIXTURE.admitted.evidence.observedGates.join(", ")} observed green on this exact commit. The relay's require-verdict rule admits this commit on refs/heads/main.`,
  );
  assert.equal(model.notRunSentence, CODING_SESSION_LAND_NOT_RUN_SENTENCE);
  assert.match(model.notRunSentence, /irreversible/);
  assert.match(model.notRunSentence, /holds no checkout/);
  assert.match(model.notRunSentence, /credential lives in your shell/);
});

test("L8.2: a refusal prints §1j's string verbatim behind §1l's prefix", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.refused),
    resolveWho,
  });
  assert.equal(model.state, "refused");
  assert.equal(model.command, null);
  // `refused` carries gate rows, so no disclosure is appended and §1j's copy
  // is the whole sentence.
  assert.equal(FIXTURE.refused.gateRowsRead, true);
  assert.equal(
    model.sentence,
    `Not ready to land: ${FIXTURE.refused.refusalReason}`,
  );
  assert.match(
    model.sentence,
    /require-verdict is set and no mission verdict names this commit/,
  );
});

test("L8.2: an ungoverned repository says so and still shows the verdict it read", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.ungoverned),
    resolveWho,
  });
  assert.equal(model.state, "ungoverned");
  assert.equal(model.command, null);
  assert.equal(
    model.sentence,
    `This repository has no require-verdict rule, so nothing here gates the push. The mission's newest verdict is ${FIXTURE.ungoverned.newestVerdict.decision} by ${FIXTURE.ungoverned.newestVerdict.authorPubkey.slice(0, 8)} over report ${FIXTURE.ungoverned.newestVerdict.reportEventId.slice(0, 8)}.`,
  );
});

test("L8.2: no repository record is unknown, never 'no rule', and says which fact it is", () => {
  const noRepoRef = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.unknown),
    repositoryUnknownReason: "no-repo-ref",
    resolveWho,
  });
  assert.equal(noRepoRef.state, "unknown");
  assert.equal(
    noRepoRef.sentence,
    "This session's creates name no repository, so nothing here can say what gates a push.",
  );

  // A named repository whose announcement did not reach this view is a
  // different fact, and "not read" is the honest word for it — never "no rule".
  const notRead = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.unknown),
    repositoryUnknownReason: "not-read",
    resolveWho,
  });
  assert.equal(notRead.state, "unknown");
  assert.equal(
    notRead.sentence,
    "The repository this session names was not read here, so nothing can say what gates a push.",
  );
  for (const model of [noRepoRef, notRead]) {
    assert.notEqual(model.state, "ungoverned");
    assert.ok(!/no require-verdict rule/.test(model.sentence));
  }
});

test("L8.2: an approval scoped to another branch is refused, with §1j's own words", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.approvedForAnotherRef),
    resolveWho,
  });
  assert.equal(model.state, "refused");
  assert.equal(model.command, null);
  assert.equal(
    model.sentence,
    `Not ready to land: ${FIXTURE.approvedForAnotherRef.refusalReason}`,
  );
  assert.match(
    model.sentence,
    /is approved for release, and this is a different ref\. A verdict admits a commit to the branch its report named\./,
  );
});

test("L28: the no-verdict string says which search produced it", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.refused),
    resolveWho,
  });
  // REVIEW-L8 F2 pinned the relay's two caps here, because this sentence used
  // to claim the relay's own search. Finding 56: this screen evaluates the ONE
  // mission it is showing, and the relay sweeps the pusher's seats, the
  // project's session channels or the bound channel. Repeating the relay's
  // bounds here would disclose a search this adapter never ran.
  assert.match(
    model.sentence,
    /Searched only mission [0-9a-f-]+, the one this screen is showing\./,
  );
  assert.match(model.sentence, /An older ruling can fall outside both\./);
});

// ── finding 33: the Land control names the founders ──────────────────────

test("L18: every state carries the founder line, and the viewer's standing", () => {
  // Every fixture but `founderPush` is a **seat's** push since the 2026-09-03
  // ruling, so the viewer is deliberately not a founder in those. The line is
  // on the screen in every state either way — that is what L18 pinned — and
  // the standing it states must track the fixture rather than a constant.
  for (const key of ["founderPush", "admitted", "refused", "ungoverned"]) {
    const model = codingSessionMissionLandModel({
      result: decodeCodingSessionLandResult(FIXTURE[key]),
      resolveWho,
    });
    assert.match(model.foundersSentence, /^Founders: the founder\./);
    assert.match(
      model.foundersSentence,
      FIXTURE[key].viewerIsFounder
        ? /You are one of them\./
        : /You are not one of them,/,
    );
    // Lane L26: any founder may set or remove a rule with a signed rule
    // record; the announcement's own rows still belong to its signer. The
    // retired clause is asserted absent so it cannot drift back.
    assert.match(
      model.foundersSentence,
      /Any founder can set or remove a rule; the announcement's own rules stay with the founder\./,
    );
    assert.ok(
      !model.foundersSentence.includes("only that key can rewrite"),
      `the retired signer-only clause must not come back: ${model.foundersSentence}`,
    );
    assert.ok(
      !model.foundersSentence.includes("was not read here"),
      `a read roster is not disclosed as unread: ${model.foundersSentence}`,
    );
    assert.equal(model.viewerIsFounder, FIXTURE[key].viewerIsFounder);
  }
});

test("L18: a viewer who founded nothing is told so, not left guessing", () => {
  const other = "3d".repeat(32);
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult({
      ...FIXTURE.refused,
      founders: [FIXTURE.refused.newestVerdict.authorPubkey, other],
      viewerIsFounder: false,
      rosterRead: false,
    }),
    resolveWho,
  });
  assert.equal(model.viewerIsFounder, false);
  assert.match(model.foundersSentence, /You are not one of them/);
  assert.match(
    model.foundersSentence,
    /The project roster was not read here/,
    "an unread roster is disclosed on the screen too",
  );
  assert.ok(
    model.foundersSentence.includes(other.slice(0, 8)),
    `the second founder is named: ${model.foundersSentence}`,
  );
});

test("L18: with no repository record the line is about the read, not the repo", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.unknown),
    resolveWho,
  });
  assert.equal(model.state, "unknown");
  assert.equal(
    model.foundersSentence,
    "No repository record reached this view, so nothing here can name its founders.",
  );
  assert.equal(model.viewerIsFounder, false);
});

test("L18: a decoder that loses the founder set is a loud failure", () => {
  for (const key of [
    "founders",
    "foundersNote",
    "viewerIsFounder",
    "rulesSigner",
    "rosterRead",
  ]) {
    const { [key]: dropped, ...missing } = FIXTURE.admitted;
    assert.notEqual(dropped, undefined);
    assert.throws(
      () => decodeCodingSessionLandResult(missing),
      /malformed response/,
      `dropping ${key} must throw`,
    );
  }
});

test("L22: arm (B) says the gates were green on this commit, and names them", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.observedGates),
    resolveWho,
  });
  const evidence = FIXTURE.observedGates.evidence;
  assert.equal(evidence.arm, "observed-gates");
  assert.equal(model.state, "ready");
  assert.equal(
    model.command,
    `git push origin ${evidence.headSha}:refs/heads/main`,
  );
  assert.equal(
    model.approvalSentence,
    `Gates observed green on ${evidence.headSha.slice(0, 8)} — ready. ${evidence.observedGates.join(", ")} were each watched passing on this exact commit, over a clean worktree, by this mission's own provider. No person has ruled on it, and this mission requires no verifier.`,
  );
  // The same mission's own newest verdict is `changes-requested`: what admits
  // this push is the gate rows, and the sentence claims no approval it does
  // not have.
  assert.ok(!/Approved by/.test(model.approvalSentence));
  assert.ok(!/did not refute/.test(model.approvalSentence));
});

test("L27: arm (C) names the gates it also stood on, and never only the verifier", () => {
  const evidence = FIXTURE.admitted.evidence;
  assert.equal(evidence.arm, "verifier-verdict");
  assert.ok(
    evidence.observedGates.length > 0,
    "an arm (C) admission stands on gate rows too",
  );
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.admitted),
    resolveWho,
  });
  for (const gate of evidence.observedGates) {
    assert.ok(
      model.approvalSentence.includes(gate),
      `the confirm step names ${gate}: ${model.approvalSentence}`,
    );
  }
});

test("L27: a refusal over rows this view never read says which it is", () => {
  const unread = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.verifiedButGatesNotGreen),
    resolveWho,
  });
  assert.equal(FIXTURE.verifiedButGatesNotGreen.gateRowsRead, false);
  assert.ok(
    unread.sentence.endsWith(CODING_SESSION_LAND_NO_GATE_ROWS_READ),
    unread.sentence,
  );
  // The same disclosure must NOT appear when the rows did reach the screen:
  // there the gate sentence is a fact about the mission.
  const read = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.refused),
    resolveWho,
  });
  assert.equal(FIXTURE.refused.gateRowsRead, true);
  assert.ok(!read.sentence.includes(CODING_SESSION_LAND_NO_GATE_ROWS_READ));
});

test("L27: a clearance with no gate rows is refused, naming both halves", () => {
  const model = codingSessionMissionLandModel({
    result: decodeCodingSessionLandResult(FIXTURE.verifiedButGatesNotGreen),
    resolveWho,
  });
  assert.equal(model.state, "refused");
  assert.equal(model.command, null);
  assert.match(model.sentence, /^Not ready to land: verifier /);
  assert.match(model.sentence, /also needs every required gate observed green/);
  assert.match(model.sentence, /cargo fmt/);
});
