import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { decodeNativeCodingSessionTeamFoldResponse } from "./invokeCodingSessionTeamFold.ts";

// Generated by the Rust adapter itself, not by hand: see
// `the_typescript_decoder_fixture_is_this_adapter_s_real_output` in
// desktop/src-tauri/src/commands/coding_session_team_fold_tests.rs. A
// hand-written fixture is exactly what let this decoder stay green (7310/7310)
// while it would have thrown for every real session (REVIEW-B1c B1).
const FIXTURE = JSON.parse(
  readFileSync(
    resolve(
      dirname(fileURLToPath(import.meta.url)),
      "codingSessionTeamFoldAdapterResponse.fixture.json",
    ),
    "utf8",
  ),
);

test("the decoder accepts the adapter's own serialized response", () => {
  const decoded = decodeNativeCodingSessionTeamFoldResponse(FIXTURE);
  assert.equal(decoded.schema, "buzz-coding-session-team-fold-adapter/v1");
  assert.equal(decoded.implementation, "buzz-core");
  // The three collections this decoder previously rejected outright.
  assert.equal(decoded.notes.length, 1);
  assert.deepEqual(Object.keys(decoded.notes[0]).sort(), [
    "authorPubkey",
    "eventId",
    "refs",
  ]);
  assert.equal(decoded.decisions.length, 1);
  assert.deepEqual(Object.keys(decoded.decisions[0]).sort(), [
    "answerId",
    "answeredBy",
    "blocks",
    "heldOn",
    "requestId",
  ]);
  assert.equal(decoded.decisions[0].heldOn, "founder");
  assert.equal(decoded.decisions[0].answeredBy, null);
  assert.equal(decoded.decisions[0].answerId, null);
  assert.deepEqual(Object.keys(decoded.waitingOnDecision).sort(), [
    "heldOn",
    "requestId",
  ]);
  // Waiting on a person is not a terminal, and neither is a held completion.
  assert.equal(decoded.canonicalTerminal, null);
  assert.equal(decoded.pendingCompletion, null);
  // Ledger 183(g): the missing link crosses the boundary, so the app no
  // longer shows the three nulls the CLI stopped printing.
  assert.deepEqual(decoded.assignments[0].awaiting, {
    link: "disposition",
    owedByRole: "lead",
    owedByActor: null,
  });
});

test("the fixture carries exactly the adapter's top-level key set", () => {
  assert.deepEqual(Object.keys(FIXTURE).sort(), [
    "assignments",
    "canonicalTerminal",
    "conflicts",
    "context",
    "decisions",
    "excluded",
    "implementation",
    "includedEventIds",
    "inputEventIds",
    "notes",
    "pendingCompletion",
    "schema",
    "unseatedReports",
    "waitingOnDecision",
  ]);
});

test("a response missing any of the three new keys is refused", () => {
  for (const key of ["notes", "decisions", "waitingOnDecision"]) {
    const { [key]: _dropped, ...without } = FIXTURE;
    assert.throws(
      () => decodeNativeCodingSessionTeamFoldResponse(without),
      /malformed response/,
      `dropping ${key} must be refused, never read as "nothing was said"`,
    );
  }
});

test("the new collections are validated field by field", () => {
  const bad = [
    { ...FIXTURE, notes: [{ ...FIXTURE.notes[0], extra: 1 }] },
    { ...FIXTURE, notes: [{ ...FIXTURE.notes[0], refs: ["nothex"] }] },
    { ...FIXTURE, notes: "not an array" },
    {
      ...FIXTURE,
      decisions: [{ ...FIXTURE.decisions[0], heldOn: "lead" }],
    },
    {
      ...FIXTURE,
      decisions: [{ ...FIXTURE.decisions[0], answerId: "nothex" }],
    },
    {
      ...FIXTURE,
      decisions: [{ ...FIXTURE.decisions[0], blocks: "not an array" }],
    },
    {
      ...FIXTURE,
      waitingOnDecision: { requestId: "nothex", heldOn: "founder" },
    },
    {
      ...FIXTURE,
      waitingOnDecision: { requestId: FIXTURE.decisions[0].requestId },
    },
  ];
  for (const value of bad) {
    assert.throws(
      () => decodeNativeCodingSessionTeamFoldResponse(value),
      /malformed response/,
    );
  }
});

test("heldOn accepts the founder token and a 64-hex actor, nothing else", () => {
  const actor = "ab".repeat(32);
  for (const heldOn of ["founder", actor]) {
    const value = {
      ...FIXTURE,
      decisions: [{ ...FIXTURE.decisions[0], heldOn }],
      waitingOnDecision: { ...FIXTURE.waitingOnDecision, heldOn },
    };
    assert.equal(
      decodeNativeCodingSessionTeamFoldResponse(value).decisions[0].heldOn,
      heldOn,
    );
  }
  for (const heldOn of ["Founder", "", "lead", actor.toUpperCase()]) {
    assert.throws(
      () =>
        decodeNativeCodingSessionTeamFoldResponse({
          ...FIXTURE,
          decisions: [{ ...FIXTURE.decisions[0], heldOn }],
        }),
      /malformed response/,
    );
  }
});
