// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as indexRouteImport } from "./routes/index";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as reposDotrepoIdDotsessionsRouteImport } from "./routes/repos.$repoId.sessions";
import { Route as reposDotrepoIdDotsessionsDotsessionRefRouteImport } from "./routes/repos.$repoId.sessions.$sessionRef";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdDotsessionsRoute =
  reposDotrepoIdDotsessionsRouteImport.update({
    id: "/repos/$repoId/sessions",
    path: "/repos/$repoId/sessions",
    getParentRoute: () => rootRouteImport,
  } as any);
const reposDotrepoIdDotsessionsDotsessionRefRoute =
  reposDotrepoIdDotsessionsDotsessionRefRouteImport.update({
    id: "/repos/$repoId/sessions/$sessionRef",
    path: "/repos/$repoId/sessions/$sessionRef",
    getParentRoute: () => rootRouteImport,
  } as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/sessions": typeof reposDotrepoIdDotsessionsRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
  "/repos/$repoId/sessions/$sessionRef": typeof reposDotrepoIdDotsessionsDotsessionRefRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/sessions": typeof reposDotrepoIdDotsessionsRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
  "/repos/$repoId/sessions/$sessionRef": typeof reposDotrepoIdDotsessionsDotsessionRefRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/sessions": typeof reposDotrepoIdDotsessionsRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
  "/repos/$repoId/sessions/$sessionRef": typeof reposDotrepoIdDotsessionsDotsessionRefRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/sessions"
    | "/repos/$repoId/blob/$"
    | "/repos/$repoId/sessions/$sessionRef";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/sessions"
    | "/repos/$repoId/blob/$"
    | "/repos/$repoId/sessions/$sessionRef";
  id:
    | "__root__"
    | "/"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/sessions"
    | "/repos/$repoId/blob/$"
    | "/repos/$repoId/sessions/$sessionRef";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  reposRoute: typeof reposRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  reposDotrepoIdDotsessionsRoute: typeof reposDotrepoIdDotsessionsRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
  reposDotrepoIdDotsessionsDotsessionRefRoute: typeof reposDotrepoIdDotsessionsDotsessionRefRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/sessions": {
      id: "/repos/$repoId/sessions";
      path: "/repos/$repoId/sessions";
      fullPath: "/repos/$repoId/sessions";
      preLoaderRoute: typeof reposDotrepoIdDotsessionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/sessions/$sessionRef": {
      id: "/repos/$repoId/sessions/$sessionRef";
      path: "/repos/$repoId/sessions/$sessionRef";
      fullPath: "/repos/$repoId/sessions/$sessionRef";
      preLoaderRoute: typeof reposDotrepoIdDotsessionsDotsessionRefRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  reposRoute: reposRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  reposDotrepoIdDotsessionsRoute: reposDotrepoIdDotsessionsRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
  reposDotrepoIdDotsessionsDotsessionRefRoute:
    reposDotrepoIdDotsessionsDotsessionRefRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
