import path from "node:path";
import { createRequire } from "node:module";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

const require = createRequire(import.meta.url);
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  // Memory Explorer's parser runs without a DOM. The package's browser
  // decoder uses document.createElement; its default export uses a static table.
  worker: {
    plugins: () => [
      {
        name: "memory-explorer-worker-entities",
        enforce: "pre",
        resolveId(source) {
          if (source !== "decode-named-character-reference") return null;
          return require.resolve(source, {
            paths: [path.dirname(require.resolve("mdast-util-from-markdown"))],
          });
        },
      },
    ],
  },
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
      "@model-capabilities-manifest": path.resolve(
        __dirname,
        "../scripts/model-capabilities.json",
      ),
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
